version: "3"
services:
  caddy:
    build: ./caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./opt:/opt"

  php:
      build: ./php
      ports:
        - "9000:9000"
      volumes:
        - "./opt:/opt"
